### ISSUE TITLE
Lokalizacja: świat

### ISSUE THREAD

**Issue by DariusKusnierz** [DariusKusnierz/Project-New-Dimension#34]
- [x] tekstura podłoża #35 
- [x] tekstura dróg #35 
- [x] zrobić drogi #43 
- [x] tekstura kamieni/skał #39 
- [x] zrobić teren skalisty #39 
- [x] zrobić teren dla jaskini #36
